export AUDACITY_PATH="${HOME}/lib/audacity-data"
export BROWSER="/usr/bin/firefox"
export EDITOR="/usr/bin/nvim"
export ELINKS_CONFDIR="${HOME}/.config/elinks"
export _FASD_DATA="${HOME}/lib/fasd"
export _FASD_VIMINFO="${HOME}/lib/viminfo"
export FZF_COMPLETION_TRIGGER="~~"
export FZF_DEFAULT_COMMAND='fd --type f'
export FZF_DEFAULT_OPTS="-m --height=40%"
export GOCACHE="${HOME}/lib/cache/go-build"
export GOPATH="${HOME}/programming/go"
export HISTFILE="${HOME}/lib/zsh_history"
export LESSHISTFILE="${HOME}/lib/lesshst"
export MANPAGER="less"
export PATH="${HOME}/bin:${HOME}/.local/bin:${HOME}/.poetry/bin:${PATH}"
export PYENV_ROOT="${HOME}/lib/pyenv"
export PYLINTHOME="${HOME}/lib/pylint.d"
export PYTHONPATH="${HOME}/bin"
export TERM="alacritty"
export XAUTHORITY="${HOME}/lib/Xauthority"
export XDG_CACHE_HOME="${HOME}/lib/cache"
export XDG_CONFIG_HOME="${HOME}/.config"
export XINITRC="${HOME}/lib/xinitrc"
export WINEPREFIX="${HOME}/lib/wine"
export WWW_HOME="${HOME}/.config/w3m"
bash /usr/bin/tdm
